sudo: false
language: python
python:
  - "3.5"
  - "3.6"
cache:
  directories:
    - travis_phantomjs
before_install:
  # Upgrade PhantomJS. Taken from:
  # https://github.com/lodash/lodash/blob/4.17.4/.travis.yml
  - |
      export PHANTOMJS_VERSION=2.1.1
      export PATH=$PWD/travis_phantomjs/phantomjs-$PHANTOMJS_VERSION-linux-x86_64/bin:$PATH
      if [ $(phantomjs --version) != $PHANTOMJS_VERSION ]; then
        rm -rf $PWD/travis_phantomjs
        mkdir -p $PWD/travis_phantomjs
        wget https://github.com/Medium/phantomjs/releases/download/v$PHANTOMJS_VERSION/phantomjs-$PHANTOMJS_VERSION-linux-x86_64.tar.bz2
        tar -xvf phantomjs-$PHANTOMJS_VERSION-linux-x86_64.tar.bz2 -C $PWD/travis_phantomjs
      fi
      phantomjs -v
install: pip install tox-travis
script: tox
env:
  global:
    - CF_CLI_VERSION=6.25.0
before_deploy:
  - export PATH=$HOME:$PATH
  - travis_retry curl -L -o $HOME/cf.tgz "https://cli.run.pivotal.io/stable?release=linux64-binary&version=$CF_CLI_VERSION"
  - tar xzvf $HOME/cf.tgz -C $HOME
deploy:
  - provider: script
    script: ./deploy-travis.sh
    skip_cleanup: true
    on:
      branch: master
      python: '3.6'
